### ISSUE TITLE
Improve initialization

### ISSUE THREAD

**Issue by mattwescott** [mattwescott/senmf#1]
Both the activations and dictionaries are initialized randomly, and only once. Better initialization would decrease the number of iterations necessary. Furthermore, because the model is non-convex, it could also improve the final performance. 

One recommended strategy is to start with many initializations, and prune them based on convergence speed.

**Comment by garret-smith** [comment]
Activation and Dictionary matrices should be passed into the fit function.  Create convenience methods to SENMF for different ways to initialize.  This solution lends itself to masking as well.
